nameOverride: ""

replicas: 1

image:
  repository: 
  tag: 
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  securityContext: {}
  #  runAsUser: 999
  #  runAsGroup: 999
  #  fsGroup: 999

env: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

resources: {}
#  limits:
#    cpu: 1000m
#    memory: 4Gi
#  requests:
#    cpu: 250m
#    memory: 100Mi

readinessProbe:
  path: 
  failureThreshold: 2
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
livenessProbe:
  path: 
  failureThreshold: 2
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

service:
  type: ClusterIP
  containerPort: 80
  annotations: {}
  labels: {}

ingress:
  enabled: false
  annotations: {}
  labels: {}
  hosts:
    - example.com
  paths:
    - /

## Labels to set container specific security contexts
containerSecurityContext:
  {}
  # capabilities:
  #   drop:
  #     - all
  # readOnlyRootFilesystem: true
